### ISSUE TITLE
The 1.3 css file errouneously shows 1.2 in the header comment

### ISSUE THREAD

**Issue by petervandenabeele** [arunagw/css-bootstrap-rails#1]
This was a bug reported and resolved a few hours ago on twitter/bootstrap.

  https://github.com/twitter/bootstrap/commit/3eafbe5c8994e884744e4a664be51ab5b6558b80

The new version on twitter/bootstrap

  https://github.com/twitter/bootstrap/blob/master/bootstrap.css

now has the correct version in the comment header.

**Comment by arunagw** [comment]
@petervandenabeele thanks for informing. :-)

**Comment by petervandenabeele** [comment]
Thanks. I tested version 0.0.3 in my base_app project and it seemed to work as expected.

**Comment by arunagw** [comment]
Cool.
