### ISSUE TITLE
rails 3.0 3.1 and engine railtie

### ISSUE THREAD

**Issue by vkill** [arunagw/css-bootstrap-rails#5]
hi, rails 3.1 should be load railtie, because "undefined method `assets' for #Rails::Engine::Configuration:0xa18a470"
so your code should be amended as

``` ruby
if ::Rails.version < "3.1"
  require "css-bootstrap-rails/railtie"
else
  require "css-bootstrap-rails/engine"
end
```

**Comment by arunagw** [comment]
It's here already. https://github.com/arunagw/css-bootstrap-rails/blob/master/lib/css-bootstrap-rails.rb

**Comment by vkill** [comment]
sorry, I made a mistake
code should be amended as

``` ruby
if ::Rails.version < "3.1"
  require "css-bootstrap-rails/engine"
else
  require "css-bootstrap-rails/railtie"
end
```

**Comment by arunagw** [comment]
When you are geting error? I mean with Normal Rails Application it's working fine.

**Comment by vkill** [comment]
No error, but engine don't support assets, your code meaning is rails 3.1 use engine.
